language: python
python:
- "2.7"
- "3.2"
- "3.3"
- "3.4"
install:
- "pip install 'setuptools>=17.1'"  # setup.py cannot upgrade setuptools, so it has to be done like this
- "python setup.py develop"
script: "python runtests.py"
